"""empty message

Revision ID: 26b4da27239a
Revises: e12b9cb4d69b
Create Date: 2023-09-25 23:14:42.090959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b4da27239a'
down_revision = 'e12b9cb4d69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id_teacher', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_teacher', sa.String(length=50), nullable=False),
    sa.Column('age_teacher', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_teacher')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher')
    # ### end Alembic commands ###
