"""empty message

Revision ID: 487b3cb2dda2
Revises: 
Create Date: 2023-09-29 19:28:19.907041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487b3cb2dda2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipline',
    sa.Column('id_discipline', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_discipline', sa.String(length=50), nullable=False),
    sa.Column('desc_discipline', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_discipline')
    )
    op.create_table('teacher',
    sa.Column('id_teacher', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_teacher', sa.String(length=50), nullable=False),
    sa.Column('age_teacher', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_teacher')
    )
    op.create_table('course',
    sa.Column('id_course', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_course', sa.String(length=50), nullable=False),
    sa.Column('desc_course', sa.String(length=100), nullable=False),
    sa.Column('publish_course', sa.Date(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id_discipline'], ),
    sa.PrimaryKeyConstraint('id_course')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    op.drop_table('teacher')
    op.drop_table('discipline')
    # ### end Alembic commands ###
