"""Initial migration.

Revision ID: 51fe05ea42dc
Revises: 
Create Date: 2023-09-22 22:58:25.901557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51fe05ea42dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id_course', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_course', sa.String(length=50), nullable=False),
    sa.Column('desc_course', sa.String(length=100), nullable=False),
    sa.Column('publish_course', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_course')
    )
    op.create_table('discipline',
    sa.Column('id_discipline', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_discipline', sa.String(length=50), nullable=False),
    sa.Column('desc_discipline', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_discipline')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discipline')
    op.drop_table('course')
    # ### end Alembic commands ###
