"""empty message

Revision ID: 6b2bcd9b147f
Revises: 
Create Date: 2023-10-12 20:05:45.222826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2bcd9b147f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipline',
    sa.Column('id_discipline', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_discipline')
    )
    op.create_table('teacher',
    sa.Column('id_teacher', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('graduate_level', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_teacher')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_adm', sa.Boolean(), nullable=True),
    sa.Column('api_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id_course', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('workload', sa.Float(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id_discipline'], ),
    sa.PrimaryKeyConstraint('id_course')
    )
    op.create_table('teacher_discipline',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id_discipline'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id_teacher'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'discipline_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_discipline')
    op.drop_table('courses')
    op.drop_table('user')
    op.drop_table('teacher')
    op.drop_table('discipline')
    # ### end Alembic commands ###
