"""empty message

Revision ID: 70967d87eb47
Revises: 376f684becc4
Create Date: 2023-10-04 18:16:37.226665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70967d87eb47'
down_revision = '376f684becc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_adm', sa.Boolean(), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=255), nullable=False))
    op.drop_column('user', 'id_adm')
    # ### end Alembic commands ###
