"""empty message

Revision ID: 766beaf4ae03
Revises: 487b3cb2dda2
Create Date: 2023-09-29 20:26:37.396849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766beaf4ae03'
down_revision = '487b3cb2dda2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_discipline',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id_discipline'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id_teacher'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'discipline_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_discipline')
    # ### end Alembic commands ###
