"""empty message

Revision ID: e12b9cb4d69b
Revises: 51fe05ea42dc
Create Date: 2023-09-24 17:32:18.588047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12b9cb4d69b'
down_revision = '51fe05ea42dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('discipline_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'discipline', ['discipline_id'], ['id_discipline'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'discipline_id')
    # ### end Alembic commands ###
